
-- use with userid in DH_UserAccount
CREATE SEQUENCE userid_seq
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;

-- use with staffno in DH_Staff
  CREATE SEQUENCE staffno_seq
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;

-- use with clientno in DH_Client
CREATE SEQUENCE clientno_seq
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;


CREATE SEQUENCE loginid_seq
  START WITH 0
  INCREMENT BY 1
  MINVALUE 0
  NOCACHE
  NOCYCLE;